title: Rogerio G. Nespolo
logo: #"/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Biomedical Engineering PhD student at the University of Illinois at Chicago, advised by Dr. Yannek Leiderman at the Vitreoretinal Microsurgical Lab. 
  <br><br>
  I obtained my Bioengineering MSc. degree at the same institution, creating a surgical guidance platform for cataract surgery using AI. My bachelor's degree in Electrical Engineering was obtained at the State University of Maringa - Brazil.
  <br><br>
  <a href="https://www.linkedin.com/in/rogerionespolo/">View My LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
