title: Rogerio G. Nespolo
logo: #"/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bioengineering MSc. 
  <br>
  Electrical Engineer
  <br><br>
  <a href="https://www.linkedin.com/in/rgnespolo/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
